version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-cicd"
s3_bucket = "aws-sam-cli-managed-default"
s3_prefix = "image-cicd"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []